---
name: Checks

on: [push]
# 깃허브 푸쉬를 할때마다 실행할 것이다 

jobs:
  test-lint:
    name: Test and Link
    runs-on: ubuntu-20.04
    # 런언 : 우분투에서 실행할 것이다. 우리가 작업하게될 운영체제를 씀. 
    # 스탭1. 도커 허브에 로그인한다 
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          # 도커로 로그인하는데 사용된다 
      # 스탭2. 체크아웃하고 
      - name: Checkout
        uses: actions/checkout@v2
      # 스탭3. 테스트하고 
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"

# docker-compose run --rm app sh -c "python manage.py test" 이거를 
# 코멘트창에 치고 엔터한다 -> OK나옴. 
      # 스탭4. 린트체크 
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"